### ISSUE TITLE
unknown locale: en_IL

### ISSUE THREAD

**Issue by OrhayBenaim** [UbuntuBudgie/budgie-welcome#175]
when trying to launch the applets app i get this error thrown into the terminal

`[Debug] Opening page: budgie-applets.html 
Traceback (most recent call last):
  File "/snap/ubuntu-budgie-welcome/31/usr/bin/budgie-welcome", line 1974, in <module>
    translations = Translations()
  File "/snap/ubuntu-budgie-welcome/31/usr/bin/budgie-welcome", line 1853, in __init__
    self.locale = str(locale.getlocale()[0])
  File "/usr/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/usr/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: en_IL
`

**Comment by fossfreedom** [comment]
OP set en_IL when installing - choose english layout and time zone of israel

**Comment by fossfreedom** [comment]
should be fixed now.  

The Snap should refresh automatically at some-point

Or you can force the refresh via this in a terminal

    snap refresh
