### ISSUE TITLE
Installing budgie applets

### ISSUE THREAD

**Issue by Vchanakya** [UbuntuBudgie/budgie-welcome#238]
Whenever trying to install a budgie applet, the following error is coming up:

Traceback (most recent call last):
  File "/snap/ubuntu-budgie-welcome/159/usr/lib/budgie-welcome/budgie-welcome-privileged-actions", line 98, in add_repos
    release_code = distro.codename().split(' ')[0].lower()
UnboundLocalError: local variable 'distro' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/ubuntu-budgie-welcome/159/usr/lib/budgie-welcome/budgie-welcome-privileged-actions", line 242, in <module>
    retval = install(fname, code)
  File "/snap/ubuntu-budgie-welcome/159/usr/lib/budgie-welcome/budgie-welcome-privileged-actions", line 159, in install
    retval = add_repos(repos, key_commands)
  File "/snap/ubuntu-budgie-welcome/159/usr/lib/budgie-welcome/budgie-welcome-privileged-actions", line 100, in add_repos
    release_code = platform.dist()[2]  # → trusty, wily, xenial
NameError: name 'platform' is not defined

**Comment by fossfreedom** [comment]
A fix was released last night.  Run in a terminal to force an update
 
    snap refresh
