### ISSUE TITLE
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'

### ISSUE THREAD

**Issue by radekmplock** [UbuntuBudgie/budgie-welcome#264]
After upgrade Ubuntu Budgie 18.04 budgie-welcome can not start:
`Traceback (most recent call last):
  File "/snap/ubuntu-budgie-welcome/308/usr/bin/budgie-welcome", line 2456, in <module>
    app.end_of_support()
  File "/snap/ubuntu-budgie-welcome/308/usr/bin/budgie-welcome", line 1886, in end_of_support
    if datetime.now() >= datetime.fromisoformat(end_of_support[systemstate.codename]):
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
`

**Comment by radekmplock** [comment]
After a replaced file in snap with version 
18ff4beb13 15 days ago

Panel start.

Instruction to replace files in snap:
https://askubuntu.com/questions/1046606/cannot-edit-system-file-snap-phpstorm-even-with-root-account-in-ubuntu-18-04
